name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Install gobump
        run: go get github.com/x-motemen/gobump/cmd/gobump

      - name: bump version
        run: |
          VERSION=${GITHUB_REF#refs/heads/}
          gobump set ${VERSION#v} -w
          git add version.go
          git commit -m "[release] bump up ${VERSION}"
          git tag -f ${VERSION}
          git push origin main
          git push origin ${VERSION}

      - name: Build
        run: make build_all

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
